
/*  PACIENTE  */
CREATE TABLE PACIENTE (
  ID_PACIENTE   NUMBER(10),
  NOME_PACIENTE VARCHAR2(100) NOT NULL,
  ENDERECO      VARCHAR2(120) NOT NULL,
  CIDADE        VARCHAR2(60) NOT NULL,
  ESTADO        VARCHAR2(2) NOT NULL,
  CPF           VARCHAR2(11) NOT NULL,
  CEP           VARCHAR2(8) NOT NULL,
  COMPLEMENTO   VARCHAR2(100),
  STATUS        VARCHAR2(1) NOT NULL,
  TELEFONE      NUMBER(11) NOT NULL,
  RG            VARCHAR2(14) NOT NULL
)
/

ALTER TABLE PACIENTE
  ADD CONSTRAINT PACIENTE_KEY PRIMARY KEY (ID_PACIENTE)
/

ALTER TABLE PACIENTE
  ADD CONSTRAINT PACIENTE_CPF_UK UNIQUE (CPF)
/

ALTER TABLE PACIENTE
  ADD CONSTRAINT PACIENTE_RG_UK UNIQUE (RG)
/

ALTER TABLE PACIENTE
  ADD CONSTRAINT STATUS_CK
  CHECK (Status in ('A','I'))
/

COMMENT ON COLUMN PACIENTE.ID_PACIENTE IS 'Primary key'
/


/*  RESPONSAVEIS  */
CREATE TABLE RESPONSAVEIS (
  ID_RESPONSAVEIS NUMBER(10) NOT NULL,
  ID_PACIENTE     NUMBER(10) NOT NULL,
  RESPONSAVEL1    VARCHAR2(100) NOT NULL,
  RESPONSAVEL2    VARCHAR2(100) NOT NULL
)
/

ALTER TABLE RESPONSAVEIS
  ADD CONSTRAINT RESPONSAVEIS_KEY PRIMARY KEY (ID_RESPONSAVEIS)
/

ALTER TABLE RESPONSAVEIS
  ADD CONSTRAINT RESPONSAVEIS_FK FOREIGN KEY (ID_PACIENTE)
  REFERENCES PACIENTE(ID_PACIENTE)
/


/*  COLABORADORES  */
CREATE TABLE COLABORADORES (
  ID_COLABORADOR       NUMBER(10) NOT NULL,
  ID_SERVICOS          NUMBER(10) NOT NULL,
  COZINHEIRA           VARCHAR2(50) NOT NULL,
  FAXINEIRA            VARCHAR2(50) NOT NULL,
  TECNICA_ENFERMAGEM   VARCHAR2(50) NOT NULL,
  MOTORISTA_AMBULANCIA VARCHAR2(50) NOT NULL,
  SALARIO              NUMBER(15,2) NOT NULL
)
/

ALTER TABLE COLABORADORES
  ADD CONSTRAINT COLABORADORES_PK PRIMARY KEY (ID_COLABORADOR)
/


/*  EQUIPE_MEDICA  */
CREATE TABLE EQUIPE_MEDICA (
  ID_EQUIPE_MEDICA   NUMBER(10) NOT NULL,
  ID_EVOLUCAO        NUMBER(10) NOT NULL,
  ENFERMEIRA         VARCHAR2(50) NOT NULL,
  TECNICA_ENFERMAGEM VARCHAR2(50) NOT NULL,
  EDUCADOR_FISICO    VARCHAR2(50) NOT NULL,
  FISIOTERAPEUTA     VARCHAR2(50) NOT NULL,
  PSICOLOGO          VARCHAR2(50) NOT NULL,
  NUTRICIONISTA      VARCHAR2(50) NOT NULL
)
/

ALTER TABLE EQUIPE_MEDICA
  ADD CONSTRAINT EQUIPE_MEDICA_PK PRIMARY KEY (ID_EQUIPE_MEDICA)
/


/*  DOENCAS  */
CREATE TABLE DOENCAS (
  ID_DOENCAS  NUMBER(10),
  NOME_DOENCA VARCHAR2(50) NOT NULL
)
/

ALTER TABLE DOENCAS
  ADD CONSTRAINT DOENCAS_PK PRIMARY KEY (ID_DOENCAS)
/

ALTER TABLE DOENCAS
  ADD CONSTRAINT DOENCAS_UK UNIQUE (NOME_DOENCA)
/


/*  EVOLUCAO_PACIENTE  */
CREATE TABLE EVOLUCAO_PACIENTE (
  ID_EVOLUCAO      NUMBER(10) NOT NULL,
  ID_PACIENTE      NUMBER(10) NOT NULL,
  ID_COLABORADOR   NUMBER(10) NOT NULL,
  ID_EQUIPE_MEDICA NUMBER(10) NOT NULL,
  DESCRITIVO       VARCHAR2(3000) NOT NULL,
  DATA_INCLUSAO    DATE NOT NULL
)
/

ALTER TABLE EVOLUCAO_PACIENTE
  ADD CONSTRAINT EVOLUCAO_PACIENTE_PK PRIMARY KEY (ID_EVOLUCAO)
/

ALTER TABLE EVOLUCAO_PACIENTE
  ADD CONSTRAINT EVOLUCAO_PACIENTE_FK FOREIGN KEY (ID_PACIENTE)
  REFERENCES PACIENTE(ID_PACIENTE)
/

ALTER TABLE EVOLUCAO_PACIENTE
  ADD CONSTRAINT EVOLUCAO_PACIENTE_COLABORADOR_FK FOREIGN KEY (ID_COLABORADOR)
  REFERENCES COLABORADORES(ID_COLABORADOR)
/

ALTER TABLE EVOLUCAO_PACIENTE
  ADD CONSTRAINT EVOLUCAO_PACIENTE_EQ_MEDICA_FK FOREIGN KEY (ID_EQUIPE_MEDICA)
  REFERENCES EQUIPE_MEDICA(ID_EQUIPE_MEDICA)
/


/*  ID_CID  */
CREATE TABLE ID_CID (
  CID_PACIENTE VARCHAR2(140) NOT NULL,
  ID_PACIENTE  NUMBER(10) NOT NULL,
  ID_DOENCAS   NUMBER(10) NOT NULL
)
/

ALTER TABLE ID_CID
  ADD CONSTRAINT ID_CID_KEY PRIMARY KEY (CID_PACIENTE)
/

ALTER TABLE ID_CID
  ADD CONSTRAINT ID_CID_FK FOREIGN KEY (ID_PACIENTE)
  REFERENCES PACIENTE(ID_PACIENTE)
/

ALTER TABLE ID_CID
  ADD CONSTRAINT ID_CID_DOENCAS_FK FOREIGN KEY (ID_DOENCAS)
  REFERENCES DOENCAS(ID_DOENCAS)
/


/*  MENSALIDADE_PACIENTE  */
CREATE TABLE MENSALIDADE_PACIENTE (
  ID_VALORPACIENTE NUMBER(10) NOT NULL,
  ID_PACIENTE      NUMBER(10) NOT NULL,
  VALOR_PAGO       VARCHAR2(10) NOT NULL,
  DATA_PAGAMENTO   DATE NOT NULL
)
/

ALTER TABLE MENSALIDADE_PACIENTE
  ADD CONSTRAINT MENSALIDADE_PACIENTE_PK PRIMARY KEY (ID_VALORPACIENTE)
/

ALTER TABLE MENSALIDADE_PACIENTE
  ADD CONSTRAINT MENSALIDADE_PACIENTE_FK FOREIGN KEY (ID_PACIENTE)
  REFERENCES PACIENTE(ID_PACIENTE)
/


